# Site settings
title: Cryptocurrency as a service
description: We are experts and connoisseurs of the crypto world. Let us bootstrap your next blockchain project.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 21Mil
user_description: 21MIL is a group of cryptocurrency developers and entrepreneurs working full time on Bitcoin, Ethereum and alternative cryptocurrency projects.
user_title: We are experts and connoisseurs of the crypto world. Let us bootstrap your next blockchain project.
email: ferdousbhai@protonmail.com
twitter_username: 
github_username: 
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
